language: java
jdk:
  - openjdk8
  - oraclejdk8
  -
before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 245b0ffb-282e-439f-ba5d-84341f92a936
